apiVersion: 1

datasources:
  # Tempo - Traces
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags: 
          - key: 'service.name'
            value: 'service'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags:
          - key: 'service.name'
            value: 'service_name'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'loki'
  # Loki - Logs
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: 'tempo'
          matcherRegex: '"trace_id":\s*"([0-9a-fA-F]{32})"'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
        - datasourceUid: 'tempo'
          matcherRegex: 'trace_id=([0-9a-fA-F]{32})'
          name: TraceID_Label
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace (Label)'
  # Prometheus - Metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: 'tempo'
          urlDisplayLabel: 'View Trace'
      timeInterval: 15s
      queryTimeout: 60s
