server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m
  max_block_bytes: 1_000_000
  complete_block_timeout: 15m

compactor:
  compaction:
    block_retention: 24h
    compacted_block_retention: 1h
    compaction_window: 1h
    max_compaction_objects: 1000000
    retention_concurrency: 10

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/traces
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: genai-coach
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /tmp/tempo/generator/traces

  processor:
    service_graphs:
      dimensions:
        - service.name
        - service.namespace
      histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
      max_items: 10000
    span_metrics:
      dimensions:
        - service.name
        - span.name
        - span.kind
        - status.code
      histogram_buckets: [0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.024, 2.048, 4.096, 8.192, 16.384]

query_frontend:
  search:
    max_duration: 0
    max_result_limit: 1000